webapp:
  cache:
    dataFile:
      enabled: true
  initialUser: scmadmin
  initialPassword: scmadmin
  stage: DEVELOPMENT
  homeDir: ./build/scm-home
  workDir: ./build/scm-work

log:
  rootLevel: WARN
  logger:
    sonia.scm: DEBUG
    com.cloudogu.scm: DEBUG
